### ISSUE TITLE
need http package update due to security issues

### ISSUE THREAD

**Issue by TetrixGauss** [abinvs-2019/gmaps_distance_find_package#5]
Hello there!

Can you update the package to get the latest http package because there is a security issue:

https://github.com/advisories/GHSA-4rgh-jx4f-qfcq

**Comment by TetrixGauss** [comment]
@abinvs-2019  any news here????

**Comment by abinvs-2019** [comment]
Sure will update, actually i dont get required time. Any PR's are welcome.

**Comment by TetrixGauss** [comment]
Great! I will create a pr today. Will you be able to merge it? @abinvs-2019

**Comment by abinvs-2019** [comment]
Merged!. Good work.

**Comment by abinvs-2019** [comment]
Can you ref the PR here, So that i can close it. Great work by the way.

**Comment by TetrixGauss** [comment]
#6  @abinvs-2019

**Comment by TetrixGauss** [comment]
@abinvs-2019 please update on pub dev

**Comment by TetrixGauss** [comment]
@abinvs-2019 any news here?

**Comment by abinvs-2019** [comment]
Actually after this PR merge to master, there is an sdk issue. Can you run it in local and come with a PR. I was not able to run and check.

**Comment by TetrixGauss** [comment]
@abinvs-2019 can you show me the error because i cannot reproduce that.

**Comment by abinvs-2019** [comment]
@TetrixGauss `Because gmaps_by_road_distance_calculator depends on http >=1.2.1 which requires SDK version ^3.3.0, version solving failed.`
The issue is with the SDK version.

**Comment by TetrixGauss** [comment]
@abinvs-2019 I ll fix it and update the package!

**Comment by abinvs-2019** [comment]
@TetrixGauss sure.

**Comment by abinvs-2019** [comment]
@TetrixGauss i am waiting for a new release😍

**Comment by TetrixGauss** [comment]
@abinvs-2019  PR #7 ready

**Comment by abinvs-2019** [comment]
@TetrixGauss  i am still facing some issues, I think it is with my flutter versions: `* Try updating the following constraints: flutter pub add flutter:'{"version":"^0.0.0","sdk":"flutter"}' flutter_polyline_points:^2.0.0 dev:flutter_test:'{"version":"^0.0.0","sdk":"flutter"}' google_maps_flutter:^2.5.3 latlong2:^0.9.1`
`flutter doctor -v`
`[✓] Flutter (Channel stable, 3.16.0, on macOS 14.4 23E214 darwin-arm64
    (Rosetta), locale en-IN)
    • Flutter version 3.16.0 on channel stable at /Users/fao/fvm/versions/old
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (8 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Users/fao/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.89.1)
    • VS Code at /Users/fao/Downloads/App Store Connect_files/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4 23E214 darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!`

**Comment by abinvs-2019** [comment]
Can you check on this if possible?

**Comment by TetrixGauss** [comment]
@abinvs-2019 what kind of issues? Try updating to the latest flutter version! I have tried the merged master and everything works fine.

**Comment by abinvs-2019** [comment]
I think my flutter version is not the latest one. Let me try it. Thanks for the help.

**Comment by TetrixGauss** [comment]
@abinvs-2019 any news? are you going to upload to pub dev please?

**Comment by abinvs-2019** [comment]
Yes, i am updating, Just got busy with some other works.

**Comment by abinvs-2019** [comment]
@TetrixGauss I have updated the new version! <3

**Comment by TetrixGauss** [comment]
@abinvs-2019 i guess it needs time? because i see the 2.0.5 version on pub dev

**Comment by TetrixGauss** [comment]
@abinvs-2019 
still 2.0.5

**Comment by abinvs-2019** [comment]
@TetrixGauss it now live.
